parser: babel-eslint

extends:
  - airbnb

plugins:
  - react
  - babel
  - jsx-a11y
  - import
  - flowtype

env:
  browser: true
  es6: true

rules:
  semi: [error, never]
  react/prop-types: off
  no-use-before-define: off